default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: admin
  password:

development:
  <<: *default
  database: household_appliances_store_development

test:
  <<: *default
  database: household_appliances_store_test
